# Generated by Django 3.0.3 on 2020-04-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='photo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
